config/routes.rb
Rails.application.routes.draw do
  root 'pages#inicio'
  # Main 
  get 'pages/main', to: 'pages#main'
  post 'pages/create_user', to: 'pages#create_user'
  post 'pages/update_hint', to: 'pages#update_hint'
  post 'pages/update_points', to: 'pages#update_points'
  get '/scoreboard', to: 'scores#scoreboard'
  post 'pokemons/create_random_pokemon', to: 'pokemons#create_random_pokemon'

  resources :pokemons do
    resources :abilities, only: [:new, :create]
  end
end

app/models/ability.rb
class Ability < ApplicationRecord
    belongs_to :pokemon
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
    has_many :abilities
 end
  

app/models/user.rb
class User < ApplicationRecord
    validates :name, presence: true
end

app/controllers/ability_controller.rb
class AbilityController < ApplicationController

      def create
        @pokemon = Pokemon.find(params[:pokemon_id])
       
        ability_name = ability_data.ability.name
        @pokemon.abilities.create(name: ability_name) # Create and associate abilities with the specific Pokemon

      
          redirect_to @pokemon, notice: 'Abilities were successfully added.'
        end
      end
    
      private
    
      def ability_params
        params.require(:ability).permit(:name)
      end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
require_relative '../../lib/assets/pokemon/pokemon_client'

class PagesController < ApplicationController
  skip_before_action :verify_authenticity_token

  

  def inicio
  end

  def create_user
    @user = User.new(name: params[:name],points: 0,hints: -1)
    if @user.save
      p @user.id
      redirect_to pages_main_path(id: @user.id)
    end
  end 

  def main
    @user = User.find_by(id: params[:id])
    @pokemon = PokemonsController.new.create_random_pokemon
    abilities = @pokemon.abilities.map { |ability| ability.name }
    @items = ["Weight " + @pokemon.weight.to_s, "Height " + @pokemon.height.to_s, "Abilities: " + abilities.join(", "),
              "Id "+@pokemon.idP.to_s]    
     @points_to_deduct = 0
  end

  def update_hint
    @user = User.find_by(id: params[:id])
    @user.hints += 1
    @user.save
    
    render json: { hints:params[:items][0..@user.hints] }
  end

  def update_points
    @user = User.find_by(id: params[:id])
    @user.points += params[:points].to_i
  
    @user.save
    render json: { points: @user.points }
  end
    

end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
    def create_random_pokemon
        pokemon_data = PokemonAPI::PokemonClient.get_random_pokemon
    
        if pokemon_data
            existing_pokemon = Pokemon.find_by(name: pokemon_data.name)
      
            if existing_pokemon
                # Pokémon already exists, do something (e.g., show a message, redirect)
                p "Pokémon #{pokemon_data.name} already exists in the database."
                @pokemon = Pokemon.find_by(name: pokemon_data.name)
            else
          # Save the fetched Pokemon data to the database
            @pokemon = Pokemon.create(
                name: pokemon_data.name,
                height: pokemon_data.height,
                weight: pokemon_data.weight,
                image_url: pokemon_data.sprites.front_default,
                idP: pokemon_data.id
            )

            if @pokemon.valid?
                # Create abilities for the created Pokemon
                create_abilities_for(@pokemon, pokemon_data.abilities)
                else
                    p "Failed to save Pokémon data."
                    return nil
                end
            end
        else
          p  "Failed to fetch Pokémon data."
          return nil
        end

        @pokemon
    end

    private 
    def create_abilities_for(pokemon, abilities_data)
        abilities_data.each do |ability_data|
          # Extract ability name from API response
          ability_name = ability_data.ability.name
    
          # Create ability and associate it with the given Pokemon
          Ability.create(
            name: ability_name,
            pokemon: pokemon
          )
        end
      end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
    def scoreboard
        @users = User.order(points: :desc)
      end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
    def index
        @user=User.all
    end
    def show
        @user=User.find(params[:id])
    end
    def new
        @user=User.new
    end
    def create
        @user=User.new(user_params)
        @user.save
        redirect_to @user
    end
    def edit
        @user=User.find(params[:id])
    end
end

app/helpers/ability_helper.rb
module AbilityHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hint_helper.rb
module HintHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/views/pages/inicio.html.erb
<%= stylesheet_link_tag 'application', media: 'all' %>

<div class="container">
    <div class="header">
        <%= image_tag('title_img.png', class: 'title-image') %>
        <%= image_tag('head_img.png', class: 'corner-image') %>
    </div>
    <div class = "user-creation">  
        <%= form_tag({controller: 'pages', action: 'create_user'}, method: 'post') do %>
            <%= label_tag(:name, "Enter your name:") %>
            <%= text_field_tag(:name) %>
            <%= submit_tag("Submit") %>
        <% end %>
    <div>
        <p>Check out the <a href="<%= scoreboard_path %>">Scoreboard</a></p>
    </div>
    </div>
    <
</div>

app/views/pages/main.html.erb
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<%= stylesheet_link_tag 'application', media: 'all' %>
<script>
    var items = <%= @items.to_json.html_safe %>;
    function updateHints() {
    $.ajax({
        url: '<%= pages_update_hint_path(id: @user.id) %>',
        type: 'post',
        data: { items: items },
        dataType: 'json',
        success: function(data) {
        var hints = data.hints;
        var list = document.getElementById("hints-list");
        list.innerHTML = "";
        for (var i = 0; i < hints.length; i++) {
            var item = document.createElement("li");
            item.setAttribute("class", "hint");
            item.innerHTML = hints[i];
            list.appendChild(item);
        }
        }
    });
    }  
    function giveUp() {
        // Redirect to the 'inicio' page
        window.location.href = '/';
    }
    function checkGuess() {
    var guessInput = document.getElementById("guess-input").value.toLowerCase(); // Get the lowercase guess
    var correctName = "<%= @pokemon.name.downcase %>"; // Get the lowercase Pokemon name

    if (guessInput === correctName) {
        // Guess is correct
        $.ajax({
        url: '<%= pages_update_points_path(id: @user.id) %>',
        type: 'post',
        data: { points: 10 }, // Adjust the points as needed
        dataType: 'json',
        success: function(data) {
            window.location.href = '/pages/main?id=<%= @user.id %>';
            var points = data.points;
            document.getElementById("points").innerHTML = "points: " + points; // Update points on screen
            document.getElementById("img").style.filter = " brightness(100%)";
            document.getElementById("message").innerHTML = "Correct Guess!";
       
        }
        });
        // refresh screen
    } else {
        window.location.href = '/';
    }
    }

</script>
<div class="container">
    <div class="header">
        <%= image_tag('title_img.png', class: 'title-image') %>
        <%= image_tag('head_img.png', class: 'corner-image') %>
    </div>
    <div class="main">
        <div class ="left-col">
            <%# image is @pokemon.image_urlt %>
            <%= image_tag(@pokemon.image_url, class: 'pokemon-img', id: 'img') %>
        </div>
        <div class ="right-col">
            <h1 class="title"><strong><%= @user.name%></strong></h1>
            <h1 id= "points">points: <%=@user.points%></h1>
            <!-- <<h1 class="title"><strong>DEBUG:  <%= @pokemon.name%></strong></h1> -->
            <h1 class="title"><strong>Who's that Pokemon?</strong></h1>
            <div class="top-input">
                <input type="text" class="input-box" id="guess-input" placeholder="Pokemon name" />
                <button class="guess-button" onclick="checkGuess()">
                    Guess
                </button>
            </div>
            <div class="hint-box">
                <ol class="hints" id="hints-list">
                    
                </ol>
            </div>
            <div class="bottom-button">
                <button class="hint-button" onclick="updateHints()">
                Get a hint
                </button>
                <button class="give-up-button" onclick="giveUp()">
                    Give up
                </button>
             
            </div>
            <h2 = "message">  </h2>
        </div>
    </div>
</div>

app/views/scores/scoreboard.html.erb
<%= stylesheet_link_tag 'application', media: 'all' %>
<div class="container">
    <div class="header">
        <%= image_tag('title_img.png', class: 'title-image') %>
        <%= image_tag('head_img.png', class: 'corner-image') %>
    </div>
    <h1>Scoreboard</h1>
    <div class="main">
    
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Points</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.name %></td>
              <td><%= user.points %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
        
    </div>
</div>

app/views/shared/_list_item.html.erb
<li>New list item</li>